# Generated by Django 4.1.13 on 2024-11-26 17:21

import django.core.validators
from django.db import migrations, models
import exam_project.core.custom_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(4), exam_project.core.custom_validators.validate_all_letters], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), exam_project.core.custom_validators.validate_all_letters], verbose_name='Last Name')),
                ('passcode', models.CharField(max_length=6, validators=[exam_project.core.custom_validators.validate_passcode])),
                ('pets_number', models.PositiveSmallIntegerField(verbose_name='Pets Number')),
                ('info', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Profile Image URL')),
            ],
        ),
    ]
